networks:
   docker-base-net:
      ipam:
         driver: default

services:
   led:
      image: trucktrack/led:latest
      container_name: trucktrack-led
      restart: on-failure

      networks:
         - docker-base-net
      ports:
         - 9090:9090
