networks:
  docker-base-net:
    ipam:
      driver: default

services:
  led:
    image: trucktrack/led:latest
    container_name: trucktrack-led
    restart: on-failure

    networks:
      - docker-base-net
    ports:
      - "9090:9090"

    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/serial1:/dev/serial1"
      - "/dev/vhci:/dev/vhci"
    volumes:
      - ../../../sys/class/gpio:/gpio
      - ../../../run/dbus:/dbus
      - ../../../usr/bin/bluetoothctl:/bluetoothctl
